"""initial schema

Revision ID: fac2a232ed22
Revises: 
Create Date: 2026-04-16 19:25:44.551492
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fac2a232ed22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basis_decomposition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gpu_sku', sa.String(length=100), nullable=False),
    sa.Column('total_variance', sa.Float(), nullable=False),
    sa.Column('variance_from_region', sa.Float(), nullable=False),
    sa.Column('variance_from_commitment', sa.Float(), nullable=False),
    sa.Column('variance_from_bundle', sa.Float(), nullable=False),
    sa.Column('variance_from_provider', sa.Float(), nullable=False),
    sa.Column('residual_variance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_basis_decomp_date_gpu', 'basis_decomposition', ['date', 'gpu_sku'], unique=False)
    op.create_table('daily_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gpu_sku', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=False),
    sa.Column('p25_price', sa.Float(), nullable=False),
    sa.Column('p75_price', sa.Float(), nullable=False),
    sa.Column('normalized_median_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_agg_date_gpu', 'daily_aggregates', ['date', 'gpu_sku'], unique=False)
    op.create_table('raw_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gpu_model_reported', sa.String(length=200), nullable=False),
    sa.Column('price_hourly', sa.Float(), nullable=False),
    sa.Column('region_reported', sa.String(length=200), nullable=True),
    sa.Column('commitment_type_reported', sa.String(length=100), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_obs_collected_gpu_provider', 'raw_observations', ['collected_at', 'gpu_model_reported', 'source'], unique=False)
    op.create_table('canonical_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_observation_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gpu_sku_canonical', sa.String(length=100), nullable=False),
    sa.Column('gpu_variant', sa.String(length=50), nullable=True),
    sa.Column('vram_gb', sa.Integer(), nullable=True),
    sa.Column('region_country', sa.String(length=100), nullable=True),
    sa.Column('region_state', sa.String(length=100), nullable=True),
    sa.Column('region_city', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('commitment_type', sa.String(length=50), nullable=False),
    sa.Column('vcpus_bundled', sa.Integer(), nullable=True),
    sa.Column('ram_gb_bundled', sa.Float(), nullable=True),
    sa.Column('storage_gb_bundled', sa.Float(), nullable=True),
    sa.Column('networking_type', sa.String(length=100), nullable=True),
    sa.Column('verification_tier', sa.String(length=50), nullable=True),
    sa.Column('price_usd_per_hour', sa.Float(), nullable=False),
    sa.Column('normalized_price_usd_per_hour', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['raw_observation_id'], ['raw_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canonical_collected_gpu_provider', 'canonical_offers', ['collected_at', 'gpu_sku_canonical', 'provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_canonical_collected_gpu_provider', table_name='canonical_offers')
    op.drop_table('canonical_offers')
    op.drop_index('ix_raw_obs_collected_gpu_provider', table_name='raw_observations')
    op.drop_table('raw_observations')
    op.drop_index('ix_daily_agg_date_gpu', table_name='daily_aggregates')
    op.drop_table('daily_aggregates')
    op.drop_index('ix_basis_decomp_date_gpu', table_name='basis_decomposition')
    op.drop_table('basis_decomposition')
    # ### end Alembic commands ###
